version: '3.8'

services:
  yt-bot:
    build: .
    container_name: yt-bot
    depends_on:
      - my_sql
    environment:
      - TOKEN=${TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - STORAGE_DIR=${STORAGE_DIR}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - .:/app
    command: ["python", "main.py"]
  
  my_sql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: discord_playlist
    ports:
      - "3306:3306"
    volumes:
      - ./discord_playlist.sql:/docker-entrypoint-initdb.d/init.sql:ro